zerror: fix build due to SIGSTKSZ no longer being statically-defined
SIGSTKSZ is now a run-time variable and so static keyword is removed
from affected variable.

Reference: https://lists.gnu.org/archive/html/bug-m4/2021-03/msg00000.html